name: Python repo workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make env install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with coverage and unittest
      run: |
        make test
